version: '3'

services:
    api:
        image: img-sem-api
        container_name: con-sem-api
        ports: 
            - "8080:8080"
        volumes:
            - db:/app

    monitoring:
        image: img-sem-monitoring
        container_name: con-sem-monitoring
        ports:
            - "8081:8081"
        volumes:
            - db:/app

    user:
        image: img-sem-fakeuser
        container_name: con-sem-user
        ports:
            - "8082:8082"

    inventory:
        image: img-sem-fakeinventory
        container_name: con-sem-inventory
        ports:
            - "8083:8083"

volumes:
    db:
